### ISSUE TITLE
APTED not in CLI

### ISSUE THREAD

**Issue by SomeUserName1** [DatabaseGroup/tree-similarity#7]
Hi

Is there a reason why APTED isn't included in the CLI so far? (considering the develop branch)
It's used in the 2019 experiments cf [here](https://frosch.cosy.sbg.ac.at/mpawlik/ted-experiments/blob/develop/src/ted_algs/ted_algs_experiments.h#L46) and [here](https://frosch.cosy.sbg.ac.at/mpawlik/ted-experiments/blob/develop/src/ted_algs/ted_algs_experiments.cc#L322).

Is the most straight forward method of using this code to provide an own binary including APTED and running it with the desired parameters (as in the experiments) or to alter the CLI code and just use the binary generated by compiling this repository (as with Zhang & Shasha)?

 (I guess the structs and the fancy template functions are not necessary if i only want APTED without logging and bench marking the algorithms but just using it)

Cheers,
Fabian

**Comment by mateuszpawlik** [comment]
Thanks Fabian for the comment.

The reason is that there is no CLI at the moment. What is there, is a leftover of some earlier attempts of starting this library. Currently I'm refactoring most of the code on the `tree-indexer` branch. Once I'm done with it, I'll continue with command line and documentations for developers and users.

There is an older Java version of APTED with CLI here: https://github.com/DatabaseGroup/apted

If you need anything particular please let me know by email. I may have a solution.
